Задача 2
Sosmunk/JokeBot pull request #32
Opened 2023-12-20 19:46 UTC by Lapoushko

2023-12-21 09:39 UTC, vpyzhyanov commented
Это как так? Сам создал, зам закоммитил, сам смёржил. Зачем тогда всё это?

![image](https://github.com/Sosmunk/JokeBot/assets/71599019/1842c628-f9f0-41d7-9e2c-f0dfd5027722)

2023-12-21 11:13 UTC, vpyzhyanov requested changes
Очень много ошибок по ООП

2023-12-21 11:13 UTC, vpyzhyanov commented on src/main/java/org/bot/service/JokeServiceImpl.java
> +            return vkChatLastJokes.getOrDefault(chatId, null);
Вон оно что.

1. Перегрузили класс ответственностью
2. Надругались над инкапсуляцией. Хотя говорили: 

> Мы боимся нарушить ооп. Ведь CommandProcessor не должен был знать ничего о ботах

А сами в сервисах открываете всю поднаготную.

Да и вообще зачем вам это - непонятно. Какой смысл делить последние шутки по разным платформам. Да ещё и так неудачно это реализовали, не гибко.

- `chatId` - уже разделяет всё по разным платформам, так что тянуть сюда `ChatPlatform` вообще не было никакого смысла. Вроде даже у них формат разный
- У вас в постановке не было такой задачи
- Реализация не универсальная и не предполагает расширение, если добавится ещё одна чат-бот платформа, то придётся переписывать кучу кода и вы обязательно что-нибудь забудете.

Предлагаю вам всё это убрать

2023-12-21 11:13 UTC, vpyzhyanov commented on src/main/java/org/bot/service/JokeServiceImpl.java
> +            return telegramChatLastJokes.getOrDefault(chatId, null);
метод используете не по назначению. Обычный get возвращает null, его и используйте.

2023-12-21 11:13 UTC, vpyzhyanov commented on src/main/java/org/bot/service/JokeServiceImpl.java
> +        } else if (chatPlatform == ChatPlatform.VK) {
весь код наполнен этими ифами, ужас

2023-12-21 11:13 UTC, vpyzhyanov commented on src/test/java/org/bot/command/CommandProcessorTest.java
> +    private final static String firstJoke = """
константы именуются ВОТ_ТАК

2023-12-21 11:13 UTC, vpyzhyanov commented on src/test/java/org/bot/command/CommandProcessorTest.java
> +        this.testJoke.setId(1);
надо было конструктор сделать подходящий и не заниматься такими вещами

2023-12-21 11:13 UTC, vpyzhyanov commented on src/test/java/org/bot/command/CommandProcessorTest.java
> +    private final ChatPlatform chatPlatform = ChatPlatform.TELEGRAM;
убрать! commandProcessor от телеграмма зависеть не должен!

2023-12-21 11:13 UTC, vpyzhyanov commented on src/test/java/org/bot/command/CommandProcessorTest.java
> +                .updateRating(Mockito.any(Rate.class), Mockito.any(Byte.class));
проверка некорректная. Логика должна быть такой:

1. Если вы проверяете, что метод вызывался, то надо проверять, что он вызывался с **правильными параметрами**
2. Если вы проверяете, что метод НЕ вызывался, то надо проверять, что при **любых** параметрах не вызывался

2023-12-21 11:13 UTC, vpyzhyanov commented on src/test/java/org/bot/command/CommandProcessorTest.java
> +        for (int i = 2; i < 6; i++) {
привыкайте использовать `<=`

2023-12-21 11:13 UTC, vpyzhyanov commented on src/test/java/org/bot/command/CommandProcessorTest.java
> +                            Mockito.any(Rate.class),
аналогично, нужно проверять, что мы обновили правильный рейтинг правильного анекдота

2023-12-21 11:16 UTC, vpyzhyanov commented
Ну и рекомендую вам (опционально) максимально избегать null значений. Использовать либо Optional либо пустой список (если вы возвращаете коллекцию)

2023-12-21 12:23 UTC, Lapoushko commented on src/test/java/org/bot/command/CommandProcessorTest.java
> +        for (int i = 2; i < 6; i++) {
Исправлено

2023-12-21 12:35 UTC, Lapoushko commented on src/test/java/org/bot/command/CommandProcessorTest.java
> +                .updateRating(Mockito.any(Rate.class), Mockito.any(Byte.class));
Исправлено

2023-12-21 13:26 UTC, Lapoushko commented on src/test/java/org/bot/command/CommandProcessorTest.java
> +        this.testJoke.setId(1);
Исправлено

2023-12-21 13:27 UTC, Lapoushko commented on src/test/java/org/bot/command/CommandProcessorTest.java
> +    private final static String firstJoke = """
исправлено

2023-12-21 13:35 UTC, Lapoushko commented on src/test/java/org/bot/command/CommandProcessorTest.java
> +                            Mockito.any(Rate.class),
исправлено

2023-12-21 15:29 UTC, Lapoushko commented on src/main/java/org/bot/Joke.java
> +    public List<Rate> getRatings() {
Поправил

2023-12-21 15:34 UTC, Sosmunk commented on src/main/java/org/bot/command/RateCommand.java
> +        return this.ratingService.rateJoke(jokeId, chatId, stars);
исправлено

2023-12-21 15:34 UTC, Sosmunk commented on src/main/java/org/bot/command/RateLastCommand.java
> +        return ratingService.rateJoke(jokeId, chatId, Byte.parseByte(args));
исправлено

2023-12-21 15:37 UTC, Sosmunk commented on src/main/java/org/bot/dao/RatingDAO.java
> +    public Rate findRating(Integer jokeId, Long chatId) {
Тогда мы вернем null

2023-12-21 15:38 UTC, Sosmunk commented on src/main/java/org/bot/dao/RatingDAO.java
> +    public Rate findRating(Integer jokeId, Long chatId) {
исправлено

2023-12-21 15:47 UTC, Sosmunk commented on src/test/java/org/bot/command/CommandProcessorTest.java
> +    private final ChatPlatform chatPlatform = ChatPlatform.TELEGRAM;
Убрано

2023-12-21 15:47 UTC, Sosmunk commented on src/main/java/org/bot/Joke.java
> +    private List<Rate> ratings;
Убрано

2023-12-21 15:47 UTC, Sosmunk commented on src/main/java/org/bot/Joke.java
> +    private List<Rate> ratings;
Перенесено в RatingService

2023-12-21 15:47 UTC, Sosmunk commented on src/main/java/org/bot/Joke.java
> +                .average();
Исправлено

2023-12-21 15:48 UTC, Sosmunk commented on src/main/java/org/bot/command/BotCommand.java
> +    String execute(String args, Long chatId, ChatPlatform chatPlatform);
платформа убрана

2023-12-21 15:48 UTC, Sosmunk commented on src/main/java/org/bot/command/JokeCommand.java
> +        String averageRating = joke.getAverageRatingString();
исправлено

2023-12-21 15:53 UTC, Sosmunk commented on src/main/java/org/bot/dao/RatingService.java
> +     * @return результат операции
исправлено

2023-12-21 15:58 UTC, Sosmunk commented on src/main/java/org/bot/dao/RatingServiceImpl.java
> +public class RatingServiceImpl implements RatingService {
исправлено

2023-12-21 15:58 UTC, Sosmunk commented on src/main/java/org/bot/service/JokeService.java
> +     * @param chatPlatform чат-платформа
убрали чат платформу

2023-12-21 15:59 UTC, Sosmunk commented on src/main/java/org/bot/dao/RatingServiceImpl.java
> +        return "Анекдот оценен";
Исправлено

2023-12-21 15:59 UTC, Sosmunk commented on src/main/java/org/bot/service/JokeServiceImpl.java
> +            return vkChatLastJokes.getOrDefault(chatId, null);
Убрали

2023-12-21 15:59 UTC, Sosmunk commented on src/main/java/org/bot/service/JokeServiceImpl.java
> +            return vkChatLastJokes.getOrDefault(chatId, null);
Остался только chatId

2023-12-21 15:59 UTC, Sosmunk commented on src/main/java/org/bot/service/JokeServiceImpl.java
> +            return telegramChatLastJokes.getOrDefault(chatId, null);
исправлено

2023-12-21 16:00 UTC, Sosmunk commented on src/main/java/org/bot/service/JokeServiceImpl.java
> +        } else if (chatPlatform == ChatPlatform.VK) {
почистили от ужасных ифов

2023-12-21 20:11 UTC, Lapoushko commented on src/main/java/org/bot/Joke.java
> +    public String getAverageRatingString() {
Исправлено

2023-12-21 20:13 UTC, Lapoushko commented on src/main/java/org/bot/bot/TelegramBot.java
> +     * Метод, который получает сообщение от пользователя и отправляет ему новое в ответ
Поправил

2023-12-21 20:13 UTC, Lapoushko commented on src/main/java/org/bot/bot/keyboard/KeyboardFactory.java
> +        for (int i = 1; i < 6; i++) {
Исправлено. теперь вообще нет такого цикла

2023-12-21 20:14 UTC, Lapoushko commented on src/main/java/org/bot/bot/keyboard/KeyboardFactory.java
> +            row.add("\n" + i + "☆");
Исправили

2023-12-21 20:14 UTC, Lapoushko commented on src/main/java/org/bot/command/RateCommand.java
> +    private static final String INVALID_ARGUMENT_COUNT = "Неверное количество аргументов";
Исправлено

2023-12-29 20:10 UTC, vpyzhyanov commented on src/main/java/org/bot/bot/keyboard/KeyboardFactory.java
> +            row.add("\n" + i + "☆");
Вроде исправили, но не идеально, т.е. недостаточно, чтобы выбраться с тёмной стороны. Например и в телеграмме и в ВК встречается слово Rate, хотя это слово относится к **логике**. Им обоим всё равно какая там будет клавиатура и из каких кнопок она состоит, их ответственность просто отрисовать нужные кнопки и всё. Никакой логики!

2023-12-29 20:48 UTC, vpyzhyanov requested changes
Оценка за Git: 2 из 3 (ранее писал за что)
Оценка за ООП: 3 из 5

Замечания исправлены, но не все исправлены правильно. 
Нет тестов на `RatingService` и `JokeService`

В целом вы проделали хорошую работу, молодцы, но могли лучше.

2023-12-29 20:48 UTC, vpyzhyanov commented on src/main/java/org/bot/bot/TelegramBot.java
> +		this.rateKeyboardMarkup = createRateKeyboard();
вот она логика в телеграмм боте

2023-12-29 20:48 UTC, vpyzhyanov commented on src/main/java/org/bot/bot/TelegramBot.java
> +	public void sendMessageWithRateKeyboard(Long chatId, String message) {
снова слово Rate

2023-12-29 20:48 UTC, vpyzhyanov commented on src/main/java/org/bot/bot/VkBot.java
> +		listRate = new KeyboardUtils().getListRates();
и какая необходимость сохранять это в поле класса? Этот список нужен только в одном методе, который вызывается в следующей строчке. Нужно сделать его локальной переменной и передавать в качестве аргумента. Либо просто внутри вызывать утилитарный метод.

2023-12-29 20:48 UTC, vpyzhyanov commented on src/main/java/org/bot/bot/VkBot.java
> +		this.rateKeyboard = createRateKeyboard();
опять логика

2023-12-29 20:48 UTC, vpyzhyanov commented on src/main/java/org/bot/bot/VkBot.java
> +			logger.error("Не удалось отправить сообщение!", e);
дублирование кода. Этот и предыдущий методы практически идентичны

2023-12-29 20:48 UTC, vpyzhyanov commented on src/main/java/org/bot/bot/keyboard/KeyboardUtils.java
> +		return LIST_RATES;
зачем нужен целый класс, ради одной константы?

2023-12-29 20:48 UTC, vpyzhyanov commented on src/main/java/org/bot/bot/keyboard/KeyboardUtils.java
> +	private static final List<String> LIST_RATES = Arrays.asList("1☆", "2☆", "3☆", "4☆", "5☆");
static запрещён!

2023-12-29 20:48 UTC, vpyzhyanov commented on src/main/java/org/bot/bot/Bot.java
> +    void sendMessageWithRateKeyboard(Long chatId, String message);
локика попала туда, куда не должна была попасть. Добро пожаловать на тёмную сторону ООП. Задача бота отправлять сообщения и **больше ничего**.

**Как правильно**

Добавить ещё один метод `sendMessage`, в котором будет ещё один аргумент - клавиатура (возможно просто в виде списка строк). А уже сама клавиатура определяется при формировании сообщения, всё-таки клавиатура должна быть не одна на все команды. 

Либо создать класс Message, который будет содержать chatId, текст сообщения и кнопки. Этот вариант легче будет расширять, например можно будет добавить туда изображения или видео.

2023-12-29 20:48 UTC, vpyzhyanov commented on src/test/java/org/bot/command/CommandProcessorTest.java
> +        this.testJoke.setId(1);
Не исправлено! 
![image](https://github.com/Sosmunk/JokeBot/assets/71599019/eaf97635-f455-4308-8336-6622e868cfe4)

2023-12-29 20:48 UTC, vpyzhyanov commented on src/test/java/org/bot/command/CommandProcessorTest.java
> +		Mockito.when(jokeService.getJoke(1))
Вы уж определитесь, у вас Mock или нет? В классе определено одно, а используете вы класс по другому

Определять поведение нужно у поля `mockJokeDao`, а не у сервиса

2023-12-29 20:48 UTC, vpyzhyanov commented on src/test/java/org/bot/command/CommandProcessorTest.java
> +		Mockito.when(ratingService.getAverageRatingForJoke(1))
аналогично. Во всех остальных местах тоже

2023-12-29 20:48 UTC, vpyzhyanov commented on src/test/java/org/bot/command/CommandProcessorTest.java
> +	JokeService jokeService = new JokeServiceImpl(mockJokeDao);
инкапсуляция вышла погулять)

2024-01-08 09:09 UTC, merged