Домашняя работа по теме "Ниспадающее программирование и его преимущества"
Sosmunk/JokeBot pull request #9
Opened 2023-11-09 13:48 UTC by Sosmunk

2023-11-09 17:38 UTC, vpyzhyanov requested changes

2023-11-09 17:38 UTC, vpyzhyanov commented on src/main/java/org/bot/Main.java
> +        BotLogic telegramBotLogic = new BotLogic(new TelegramJokeBot(jokeService));
лучше использовать одну и ту же логику на всех ботов, а не создавать под каждого бота новый экземпляр. Например это важно при сохранении данных в памяти, у каждого бота будут свои данные, а это не хорошо.

2023-11-09 17:38 UTC, vpyzhyanov commented on src/main/java/org/bot/Main.java
> +        telegramBotLogic.startBot();
Логика запускает бота? А вы уверены, что именно она этим должна заниматься? Какая у ней задача?

2023-11-09 17:38 UTC, vpyzhyanov commented on src/main/java/org/bot/bots/BotLogic.java
> + * Класс для хранения логики бота
не совсем корректно говорить "хранение логики". Её невозможно хранить, её нужно реализовывать и использовать)

2023-11-09 17:38 UTC, vpyzhyanov commented on src/main/java/org/bot/bots/JokeBot.java
> +    // TODO: sendMessage
Пометка есть, а реализации нет, почему?

2023-11-09 17:38 UTC, vpyzhyanov commented on src/main/java/org/bot/bots/JokeBot.java
> +    void start();
А вы уверены, что этот метод необходим?

2023-11-09 17:38 UTC, vpyzhyanov commented on src/main/java/org/bot/bots/JokeBot.java
> + * Интерфейс, в котором должны
Должны что?

хм.... кажется я уже писал это замечание

2023-11-09 17:38 UTC, vpyzhyanov commented on src/main/java/org/bot/bots/JokeBot.java
> + * Интерфейс, в котором должны
И действительно. https://github.com/Sosmunk/JokeBot/pull/7#discussion_r1380705860

2023-11-09 17:38 UTC, vpyzhyanov commented on src/main/java/org/bot/bots/JokeBot.java
> +public interface JokeBot {
Странное название. В этом интерфейсе нет ни одного метода, который бы хоть как-то использовал "шутки". 

Скорее всего вы тянете имя проекта в классы без видимой на то причины. Не надо так.

2023-11-09 17:38 UTC, vpyzhyanov commented on src/main/java/org/bot/bots/TelegramJokeBot.java
> +public class TelegramJokeBot extends TelegramLongPollingBot implements JokeBot {
Вот здесь тоже "шутка", хотя этот класс к шуткам не имеет ни малейшего отношения

2023-11-09 17:38 UTC, vpyzhyanov commented on src/main/java/org/bot/bots/VkJokeBot.java
> +                String response = "Ваше сообщение " + message.getText();
похоже вы плохо слушали на лекции. Дублируется функционал

2023-11-09 17:38 UTC, vpyzhyanov commented on src/main/java/org/bot/commands/BotCommand.java
> + * Интерфейс, отвечающий за реализацию команд
Интерфейс не может отвечать за реализацию) Интерфейс - не содержит реализации, он же интерфейс, а не класс. Пишите реальную суть и цель этого интерфейса. В вашем случае это `Команда бота`, это коротко и отражает суть

2023-11-09 17:38 UTC, vpyzhyanov commented on src/main/java/org/bot/commands/CommandProcessor.java
> +    private void init() {
нет смысла выносить этот метод. Конструктор тоже отвечает за инициализацию, получается вы размазали ответственность по двум методам

2023-11-09 17:38 UTC, vpyzhyanov commented on src/main/java/org/bot/commands/CommandProcessor.java
> +        } catch (NullPointerException e) {
это исключение не может означать, что команда не найдена. Оно может возникнуть где угодно и означает только то, что вызван метод у объекта, который `null`

2023-11-09 19:02 UTC, vpyzhyanov commented on src/main/java/org/bot/Main.java
> +        JokeService jokeService = new JokeServiceImpl();
> Удивительно далеко без синглтона приходится протягивать Service до нужной логики

Если бы вы его создали там где нужно, то не пришлось бы его так далеко протягивать. Как минимум его стоит определить в `CommandProcessor`, а не здесь. Здесь он явно не нужен.

2023-12-02 13:19 UTC, vpyzhyanov commented
Похоже вы не научились игнорировать файлы

![image](https://github.com/Sosmunk/JokeBot/assets/71599019/b9a802fc-aae4-4d48-a75c-48c1a2e7d688)

2023-12-02 14:18 UTC, vpyzhyanov commented on src/main/java/org/bot/commands/BotCommand.java
> + * Интерфейс, отвечающий за реализацию команд
Не исправлено!

2023-12-02 14:23 UTC, vpyzhyanov commented on src/main/java/org/bot/Main.java
> +        JokeService jokeService = new JokeServiceImpl();
Не исправлено!

2023-12-02 17:31 UTC, vpyzhyanov requested changes
1. Прошу вспомнить что такое правила хорошего тона
2. Прошу не оставлять неисправленных замечаний
3. Снял один балл за Git за неправильное игнорирование

2023-12-02 17:31 UTC, vpyzhyanov commented on src/main/java/org/bot/utils/DataLoader.java
> +    public void populate(JokeService jokeService) {
имя метода не соответствует описанию, они говорят о разных вещах

2023-12-02 17:31 UTC, vpyzhyanov commented on src/main/java/org/bot/utils/DataLoader.java
> +     * @param jokeService jokeService
классное описание))

2023-12-02 17:31 UTC, vpyzhyanov commented on src/main/java/org/bot/utils/DataLoader.java
> +                Настоящий программист никогда не ставит комментариев. То, что писалось с трудом, должно пониматься с трудом.
сохраню себе, буду использовать когда буду рассказывать про JavaDoc)))

2023-12-02 17:31 UTC, vpyzhyanov commented on src/main/java/org/bot/utils/DataLoader.java
> +        jokeService.saveJoke(new Joke("""
дублирование кода. Кучу раз вызывается один и тот же код.

2023-12-02 17:31 UTC, vpyzhyanov commented on src/main/java/org/bot/utils/DataLoader.java
> +                Чтобы программисты писали быстрый код, им надо выдавать медленные компьютеры.
это правда))) А то расслабились все с мощными процессорами и с кучей памяти)

2023-12-02 17:31 UTC, vpyzhyanov commented on src/main/resources/logging.properties
> +.level=INFO
вы не ошиблись в заполнении? Свойства не начинаются с точки

2023-12-02 17:31 UTC, vpyzhyanov commented on src/main/resources/logging.properties
> +deng.level=FINEST
Кажется тут тоже ошибка в имени свойства

2023-12-02 17:31 UTC, vpyzhyanov commented on src/main/resources/logging.properties
Вообще-то log4j версии 2 использует файл конфигурации `log4j2.xml`

2023-12-02 17:31 UTC, vpyzhyanov commented on src/test/java/org/bot/CommandParserTest.java
> +package org.bot;
`CommandParser `находится в другом пакете

2023-12-02 17:31 UTC, vpyzhyanov commented on src/test/java/org/bot/CommandParserTest.java
> +    CommandParser commandParser = new CommandParser();
неправильный модификатор видимости

2023-12-02 17:31 UTC, vpyzhyanov commented on src/test/java/org/bot/CommandParserTest.java
> +        Assert.assertEquals("Invalid command!",commandDataExpected,commandDataActual);
все параметры слиты в один текст. Используйте форматирование

2023-12-02 17:31 UTC, vpyzhyanov commented on src/test/java/org/bot/CommandParserTest.java
> +     * Тест команды /rate <id> <stars 1-5> на отсутствие аругментов
Не надо использовать угловые скобки в JavaDoc. Если вы посмотрите его, то увидите, что описание отображается некорректно, т.к. они воспринимаются как html теги. Используйте `&lt;` и `&gt;` вместо них, либо любые другие скобки.

опечатка

2023-12-02 17:31 UTC, vpyzhyanov commented on src/test/java/org/bot/FakeService.java
> +public class FakeService implements JokeService {
1. Нет описания
2. Некорректное название, оно вводит в заблуждение. Что за фейковый сервис?

2023-12-02 17:31 UTC, vpyzhyanov commented on src/test/java/org/bot/CommandTest.java
> +public class CommandTest {
нет описания

2023-12-02 17:31 UTC, vpyzhyanov commented on src/test/java/org/bot/CommandTest.java
> +                commandProcessor.runCommand(commandData));
Вы проверили только половину функционала. Ведь бот сначала парсит команду. Тест на класс `CommandParser` не в счёт, т.к. в тестах вы вообще не контролируете даже то, что он вообще вызывается.

Если поправить ваш код так:
![image](https://github.com/Sosmunk/JokeBot/assets/71599019/94d70995-78fd-4868-8579-8fb7cfe38a27)

То все ваши тесты всё равно пройдут.

2023-12-02 17:31 UTC, vpyzhyanov commented on src/test/java/org/bot/CommandTest.java
> +    FakeService fakeService = new FakeService();
модификатор видимости

2023-12-02 17:31 UTC, vpyzhyanov commented on src/test/java/org/bot/CommandTest.java
> +                — Заходит программист в лифт, а ему надо на 12—й этаж.
дважды дублируется один и тот же текст. Надо вынести в переменную

2023-12-02 17:37 UTC, vpyzhyanov commented on src/main/java/org/bot/Main.java
> +        JokeService jokeService = new JokeServiceImpl();
хотя возможно придётся всё равно создавать `JokeService` (который на самом деле не сервис) именно тут, только из-за тестов.

2023-12-05 18:44 UTC, Sosmunk commented on src/main/java/org/bot/Joke.java
> +    private Integer id;
1. 2 147 483 647
2. Рекомендуется в документации hibernate:
https://docs.jboss.org/hibernate/orm/5.3/userguide/html_single/Hibernate_User_Guide.html#entity-pojo-identifier

2023-12-05 18:45 UTC, Sosmunk commented on src/main/java/org/bot/Joke.java
> +    private Integer id;
Вряд ли в мире существует больше двух миллиардов шуток, так что Integer будет достаточно

2023-12-05 19:08 UTC, Sosmunk commented on pom.xml
> +            <artifactId>log4j-core</artifactId>
Log4j требуется для SDK ВКонтакте
https://dev.vk.com/ru/sdk/java

2023-12-05 19:19 UTC, Sosmunk commented on src/main/java/org/bot/Joke.java
> +    private Integer id;
Конечно best practice использовать long. Если инты использовать неправильно в рамках учебного проекта, это будет исправлено.

2023-12-14 18:12 UTC, vpyzhyanov commented on src/main/java/org/bot/dao/JokeService.java
> +     * @return сохраненный анекдот
Не исправлено! Возвращаемое значение нигде не используется и должно быть удалено

2023-12-14 18:12 UTC, vpyzhyanov commented on src/main/java/org/bot/Main.java
> +        telegramBotLogic.startBot();
Ответа всё ещё нет!!! Давайте так: если я в **третий** раз напишу, что нет ответа, то сразу поставлю вам за задачу 0 без возможности исправления.

2023-12-14 18:15 UTC, vpyzhyanov commented on src/main/java/org/bot/bots/JokeBot.java
> +    void start();
Нет ответа №2!!!

Совершенно бесполезный метод, которым вы даже не пользуетесь

2023-12-14 18:25 UTC, vpyzhyanov requested changes
Да вы издеваетесь! Не исправлены первые же замечания! Не буду проверять! В чёрный список вас лучше добавлю.

Ещё раз такое повторится, поставлю сразу 0 без возможности исправления!

2023-12-14 18:25 UTC, vpyzhyanov commented on src/main/java/org/bot/bots/JokeBot.java
> +    void start();
Нет ответа №2!!!

Совершенно бесполезный метод, которым вы даже не пользуетесь

2023-12-14 18:25 UTC, vpyzhyanov commented on src/main/java/org/bot/bots/JokeBot.java
> +public interface JokeBot<T> {
Не исправлено!

2023-12-14 18:25 UTC, vpyzhyanov commented on src/main/java/org/bot/bots/JokeBot.java
> +    void sendMessage(T chatId, String message);
Не исправлено!

2023-12-14 18:25 UTC, vpyzhyanov commented on src/main/java/org/bot/bots/JokeBot.java
> +    // Если этот метод здесь не нужен, то как нам запускать бота?
Не исправлено!

2023-12-14 18:25 UTC, vpyzhyanov commented on src/main/java/org/bot/bots/TelegramJokeBot.java
> +package org.bot.bots;
Не исправлено!

2023-12-14 18:25 UTC, vpyzhyanov commented on src/main/java/org/bot/bots/TelegramJokeBot.java
> +public class TelegramJokeBot extends TelegramLongPollingBot implements JokeBot<String> {
Не исправлено! Да вы издеваетесь! Не буду проверять!

2023-12-14 19:04 UTC, Sosmunk commented on src/main/java/org/bot/Main.java
> +        telegramBotLogic.startBot();
BotLogic удалена. Мы с вами обсудили это на консультации. Просим прощения что не ответили в комментариях

2023-12-14 19:05 UTC, Sosmunk commented on src/main/java/org/bot/bots/BotLogic.java
> + * Класс для хранения логики бота
удалено

2023-12-14 19:05 UTC, Sosmunk commented on src/main/java/org/bot/bots/JokeBot.java
> +    // TODO: sendMessage
реализация сделана

2023-12-14 19:06 UTC, Sosmunk commented on src/main/java/org/bot/bots/JokeBot.java
> +    void start();
используется в main для запуска ботов

2023-12-14 19:06 UTC, Sosmunk commented on src/main/java/org/bot/bots/JokeBot.java
> + * Интерфейс, в котором должны
Исправлено

2023-12-14 19:08 UTC, Sosmunk commented on src/main/java/org/bot/commands/CommandProcessor.java
> +    private void init() {
удалено

2023-12-14 19:09 UTC, Sosmunk commented on src/main/java/org/bot/Main.java
> +        JokeService jokeService = new JokeServiceImpl();
исправлено

2023-12-14 19:09 UTC, Sosmunk commented on .gitignore
>  # .idea/modules
исправлено

2023-12-14 19:10 UTC, Sosmunk commented on .gitignore
> +/.idea/
исправлено

2023-12-14 19:10 UTC, Sosmunk commented on .gitignore
> +!/.env
исправлено

2023-12-14 19:10 UTC, Sosmunk commented on src/main/java/org/bot/Main.java
> +        dataLoader.populate(jokeService);
исправлено

2023-12-14 19:11 UTC, Sosmunk commented on src/main/java/org/bot/bots/BotLogic.java
> +public class BotLogic {
удалено

2023-12-14 19:11 UTC, Sosmunk commented on src/main/java/org/bot/bots/BotLogic.java
> +    //TODO: Отправка сообщений в нужного бота по расписанию
удалено

2023-12-14 19:12 UTC, Sosmunk commented on src/main/java/org/bot/bots/JokeBot.java
> +    // Если этот метод здесь не нужен, то как нам запускать бота?
мы используем этот метод для запуска ботов в Main

2023-12-14 19:14 UTC, Sosmunk commented on src/main/java/org/bot/bots/JokeBot.java
> +public interface JokeBot<T> {
Описали параметризацию

2023-12-14 19:16 UTC, Sosmunk commented on src/main/java/org/bot/bots/TelegramJokeBot.java
> +            String result = commandProcessor.runCommand(commandData);
исправлено

2023-12-14 19:16 UTC, Sosmunk commented on src/main/java/org/bot/bots/TelegramJokeBot.java
> +            // ---
исправлено

2023-12-14 19:17 UTC, Sosmunk commented on src/test/java/org/bot/CommandTest.java
> +    FakeService fakeService = new FakeService();
исправлено

2023-12-14 19:18 UTC, Sosmunk commented on src/test/java/org/bot/CommandTest.java
> +                — Заходит программист в лифт, а ему надо на 12—й этаж.
исправлено

2023-12-14 22:21 UTC, Lapoushko commented on src/main/java/org/bot/dao/JokeService.java
> +public interface JokeService {
JokeService относится к DAO, поскольку в нём есть save, который сохраняет анекдот в БД

2023-12-14 22:21 UTC, Lapoushko commented on src/main/java/org/bot/dao/JokeService.java
> +package org.bot.dao;
JokeService относится к DAO, поскольку в нём есть save, который сохраняет анекдот в БД

2023-12-15 08:58 UTC, Lapoushko commented on src/main/java/org/bot/bots/TelegramJokeBot.java
> +public class TelegramJokeBot extends TelegramLongPollingBot implements JokeBot {
исправлено

2023-12-15 09:02 UTC, Lapoushko commented on src/main/java/org/bot/bots/VkJokeBot.java
> +                String response = "Ваше сообщение " + message.getText();
Исправлено

2023-12-15 09:03 UTC, Lapoushko commented on src/main/java/org/bot/Main.java
> +        BotLogic telegramBotLogic = new BotLogic(new TelegramJokeBot(jokeService));
Исправлено

2023-12-15 09:05 UTC, Lapoushko commented on src/test/java/org/bot/FakeService.java
> +public class FakeService implements JokeService {
1) /**
 * Моковый сервис для тестирования функционала CommandProcessor
 */
 2) Это фейковый сервис для тестирования. Переименовали FakeJokeService

2023-12-15 09:05 UTC, Lapoushko commented on src/test/java/org/bot/CommandTest.java
> +public class CommandTest {
Исправлено. Добавлено описание

2023-12-15 09:08 UTC, Lapoushko commented on src/test/java/org/bot/CommandTest.java
> +                commandProcessor.runCommand(commandData));
Исправлено

2023-12-15 09:18 UTC, Lapoushko commented on src/main/java/org/bot/bots/JokeBot.java
> +    void start();
Исправлено

2023-12-15 09:19 UTC, Lapoushko commented on src/main/java/org/bot/bots/JokeBot.java
> +    // Если этот метод здесь не нужен, то как нам запускать бота?
Исправлено

2023-12-15 09:20 UTC, Lapoushko commented on src/main/java/org/bot/bots/JokeBot.java
> +    void sendMessage(T chatId, String message);
исправлено

2023-12-15 09:20 UTC, Lapoushko commented on src/main/java/org/bot/bots/JokeBot.java
> +public interface JokeBot<T> {
Исправили. Убрали параметризацию из-за ненадобности

2023-12-15 09:27 UTC, Lapoushko commented on pom.xml
> +            <artifactId>log4j-core</artifactId>
Теперь используется логирование

2023-12-15 09:28 UTC, Lapoushko commented on src/main/java/org/bot/bots/JokeBot.java
> +    void sendMessage(T chatId, String message);
Исправлено. Убрали параметризацию, поскольку теперь она не нужна

2023-12-15 09:28 UTC, Lapoushko commented on src/main/java/org/bot/bots/TelegramJokeBot.java
> +public class TelegramJokeBot extends TelegramLongPollingBot implements JokeBot<String> {
Исправили. Переименовали классы, которые не относятся к шуткам

2023-12-15 09:29 UTC, Lapoushko commented on src/main/java/org/bot/bots/TelegramJokeBot.java
> +package org.bot.bots;
Исправлено

2023-12-15 09:29 UTC, Lapoushko commented on src/main/java/org/bot/bots/TelegramJokeBot.java
> +    public TelegramJokeBot(CommandProcessor commandProcessor) {
Исправлено. Теперь конструктор не помечается как устаревший

2023-12-15 09:36 UTC, Lapoushko commented on src/main/java/org/bot/bots/TelegramJokeBot.java
> +            e.printStackTrace();
Исправлено

2023-12-15 09:37 UTC, Lapoushko commented on src/main/java/org/bot/bots/TelegramJokeBot.java
> +            e.printStackTrace();
Исправлено

2023-12-15 09:37 UTC, Lapoushko commented on src/main/java/org/bot/bots/VkJokeBot.java
> + * VK Бот для работы с анекдотами
Исправлено

2023-12-15 09:41 UTC, Lapoushko commented on src/main/java/org/bot/bots/VkJokeBot.java
> +        // TODO: Функционал работы с анекдотами
Исправлено

2023-12-15 09:41 UTC, Lapoushko commented on src/main/java/org/bot/bots/VkJokeBot.java
> +            //
Исправлено

2023-12-15 09:42 UTC, Lapoushko commented on src/main/java/org/bot/bots/VkJokeBot.java
> +            e.printStackTrace();
Исправлено. Теперь логгирование используется

2023-12-15 09:47 UTC, Lapoushko commented on src/main/java/org/bot/commands/GetJokeCommand.java
> + * /getJoke
Исправлено

2023-12-15 09:47 UTC, Lapoushko commented on src/main/java/org/bot/commands/GetJokeCommand.java
> +        return String.format("Анекдот №%s%n", joke.getId()) + joke.getText();
Исправлено

2023-12-15 09:48 UTC, Lapoushko commented on src/main/java/org/bot/commands/GetJokeCommand.java
> +     * Получить анекдот по id
Исправлено

2023-12-15 09:49 UTC, Lapoushko commented on src/main/java/org/bot/commands/HelpCommand.java
> +     * Получить справку о работе бота (/help)
Исправлено

2023-12-15 09:50 UTC, Lapoushko commented on src/main/java/org/bot/commands/JokeCommand.java
> +     * Получить случайную шутку (/joke)
Исправлено

2023-12-15 09:51 UTC, Lapoushko commented on src/main/java/org/bot/commands/JokeCommand.java
> +        return String.format("Анекдот №%s%n", joke.getId()) + joke.getText();
Никакого тайного смысла. Иногда синие занавески - только лишь синие занавески )
Исправили, убрали %n

2023-12-15 09:51 UTC, Lapoushko commented on src/main/java/org/bot/commands/StartCommand.java
> +     * Получить приветствие (/start)
Исправлено

2023-12-15 09:54 UTC, Lapoushko commented on src/main/java/org/bot/dao/JokeService.java
> +     * @return сохраненный анекдот
Исправлено

2023-12-15 09:54 UTC, Lapoushko commented on src/main/java/org/bot/dao/JokeServiceImpl.java
> + * Сервис, отвечающий за взаимодействие с базой данных joke
Исправлено

2023-12-15 10:07 UTC, Lapoushko commented on src/main/java/org/bot/dto/CommandData.java
> +public class CommandData {
исправлено

2023-12-15 10:07 UTC, Lapoushko commented on src/main/java/org/bot/dto/CommandParser.java
> + * Класс парсера команд, вводимых пользователем
исправлено

2023-12-15 10:08 UTC, Lapoushko commented on src/main/java/org/bot/dto/CommandParser.java
> +        if (message == null || message.isEmpty() || message.isBlank()) return new CommandData(null,null);
исправлено

2023-12-15 10:14 UTC, Lapoushko commented on src/main/java/org/bot/utils/DataLoader.java
> +    public void populate(JokeService jokeService) {
исправлено

2023-12-15 10:15 UTC, Lapoushko commented on src/main/java/org/bot/utils/DataLoader.java
> +        jokeService.saveJoke(new Joke("""
Исправлено

2023-12-15 10:16 UTC, Lapoushko commented on src/main/java/org/bot/utils/DataLoader.java
> +                Настоящий программист никогда не ставит комментариев. То, что писалось с трудом, должно пониматься с трудом.
Да, смешная шутка)

2023-12-15 10:18 UTC, Lapoushko commented on src/main/resources/logging.properties
> +deng.level=FINEST
исправлено. Мы решили убрать полностью файл logging.properties, поскольку он был не нужен

2023-12-15 10:18 UTC, Lapoushko commented on src/main/resources/logging.properties
Мы уже используем файл log4j2.xml. Исправлено

2023-12-15 10:20 UTC, Lapoushko commented on src/test/java/org/bot/CommandParserTest.java
> +    CommandParser commandParser = new CommandParser();
Исправлено

2023-12-15 10:21 UTC, Lapoushko commented on src/test/java/org/bot/CommandParserTest.java
> +        Assert.assertEquals("Invalid command!",commandDataExpected,commandDataActual);
Исправлено

2023-12-15 10:26 UTC, Lapoushko commented on src/test/java/org/bot/CommandParserTest.java
> +     * Тест команды /rate <id> <stars 1-5> на отсутствие аругментов
Удалили лишний тест. Но в местах, где используются <>, заменили на &lt; &gt;

2023-12-15 17:02 UTC, Sosmunk commented on src/main/java/org/bot/dao/JokeService.java
> +package org.bot.dao;
перенесено

2023-12-15 17:03 UTC, Sosmunk commented on src/main/java/org/bot/dao/JokeService.java
> +public interface JokeService {
онесенереп

2023-12-15 17:10 UTC, Sosmunk commented on src/main/java/org/bot/dao/JokeServiceImpl.java
> +                "jdbc:postgresql://localhost:5433/" + System.getenv("DB"));
hibernate.properties используется для общедоступных данных, логин и пароль будут задаваться из переменных окружения

2023-12-15 17:10 UTC, Sosmunk commented on src/main/java/org/bot/dao/JokeServiceImpl.java
> +                "jdbc:postgresql://localhost:5433/" + System.getenv("DB"));
ссылка для подключения к БД перенесена в hibernate.properties

2023-12-15 17:16 UTC, Sosmunk commented on src/main/java/org/bot/bots/TelegramJokeBot.java
> +            sendMessage(chatId, result);
В рамках задачи с отложенной отправкой будет использоваться данный метод.

2023-12-15 17:24 UTC, Sosmunk commented on src/main/java/org/bot/bots/VkJokeBot.java
> +            // Дублирование кода
исправлено

2023-12-15 17:28 UTC, Sosmunk commented on src/main/java/org/bot/utils/DataLoader.java
> +     * @param jokeService jokeService
исправлено

2023-12-15 17:29 UTC, Sosmunk commented on src/main/java/org/bot/dto/CommandData.java
> +package org.bot.dto;
исправлено

2023-12-15 20:00 UTC, Sosmunk commented on src/main/java/org/bot/dao/JokeServiceImpl.java
> +        Transaction transaction = session.beginTransaction();
Исправлено с использованием TransactionRunner

2023-12-15 20:00 UTC, Sosmunk commented on src/main/java/org/bot/dao/JokeServiceImpl.java
> +        Session session = sessionFactory.openSession();
теперь используется try with resources

2023-12-15 20:03 UTC, Sosmunk commented on src/main/java/org/bot/utils/DataLoader.java
> + * hibernate сейчас работает через create-drop, поэтому дублирование данных не страшно
Будет использоваться update

2023-12-15 20:04 UTC, Sosmunk commented on src/main/java/org/bot/utils/DataLoader.java
> + * hibernate сейчас работает через create-drop, поэтому дублирование данных не страшно
DataLoader убран

2023-12-15 20:30 UTC, Sosmunk commented on src/main/resources/hibernate.properties
> +hibernate.hbm2ddl.auto=create-drop
Изменено на update

2023-12-15 20:30 UTC, Sosmunk commented on src/main/resources/logging.properties
> +.level=INFO
Удалено, комментарий ниже

2023-12-16 17:58 UTC, Sosmunk commented on src/main/java/org/bot/bots/TelegramJokeBot.java
> +            // TODO: Будет дублироваться, поправить
комментарий убран

2023-12-16 17:59 UTC, Sosmunk commented on src/main/java/org/bot/dao/JokeServiceImpl.java
> +        session.close();
исправлено

2023-12-16 18:00 UTC, Sosmunk commented on src/test/java/org/bot/CommandParserTest.java
> +package org.bot;
изменилась директория CommandParser

2023-12-18 17:55 UTC, vpyzhyanov requested changes
Исправляйте последние замечания и можете мёрджить. **Задача принята**.

Для скорости не буду дожидаться исправления, а просто снижу баллы, иначе вообще ничего сдать не успеете. Но если в следующей задаче увижу, что замечания не исправлены, вас постигнет страшная кара.

2023-12-18 17:55 UTC, vpyzhyanov commented on src/main/java/org/bot/service/JokeServiceImpl.java
> +        if (getRandomJoke() == null) {
выглядит как-то искусственно и контр интуитивно. Если **случайная** шутка отсутствует, то заполняй данными. Случайности не место в коде!

Нужно создать в JokeDAO метод `isEmpty()` и взывать его

2023-12-18 17:55 UTC, vpyzhyanov commented on src/main/java/org/bot/dao/JokeDAO.java
> +                return null;
Лучше использовать Optional. Так будет очевидно, что может прийти пустое значение. А то **вы даже в JavaDoc не потрудились предупредить, что тут может вернуться null**!

2023-12-18 17:55 UTC, vpyzhyanov commented on src/main/java/org/bot/command/CommandProcessor.java
> +        return commandParser.parseMessage(command);
однострочный метод не имеет смысла. Тем более у него JavaDoc нет

2023-12-18 17:55 UTC, vpyzhyanov commented on src/test/java/org/bot/FakeJokeService.java
> +public class FakeJokeService implements JokeService {
Это ерудна какая-то. Лучше используйте мокито

1. Вы дублируете функциональность/пишете новую, да и непонятно зачем. Не надо слепо использовать трюк с отправкой сообщения, он нужен только для отправки сообщения. Тут же мокито подойдёт намного лучше.
2. Хотели замокать слой работы с данными, а совершили страшную ошибку и избавились от сервиса, хотя надо было мокать DAO.
3. Не протестирован сервис JokeService

2023-12-18 17:55 UTC, vpyzhyanov commented on src/test/java/org/bot/command/CommandTest.java
> +    private final String FIRST_JOKE = """
имя как у константы, но это не **static**

2023-12-18 17:55 UTC, vpyzhyanov commented on src/main/resources/hibernate.properties
> +hibernate.connection.url=jdbc:postgresql://localhost:5433/joker
жёстко зашили путь и имя к БД зачем-то. Нельзя так делать. Этот параметр, ровно как и логин с паролем, точно так же должны настраиваться индивидуально. 

На самом деле в репозитории файла hibernate.properties быть не должно, он должен быть заигнорирован, но должен быть его шаблон, например hibernate.properties.template, переименовав который можно заполнить все необходимые параметры, включая логин и пароль.

2023-12-18 17:55 UTC, vpyzhyanov commented on src/main/java/org/bot/util/HibernateUtils.java
> +                System.getenv("DB_PASSWORD"));
Логин и пароль от БД должны задавать там же, где все настройки БД, а именно в hibernate.properties

2023-12-18 17:55 UTC, vpyzhyanov commented on src/test/java/org/bot/command/CommandTest.java
> + * Тест обработки команд /help, /start, /joke, /getJoke &lt;id&gt;
Не надо их перечислять, по любому забудете добавить имя команды сюда, когда добавите новую команду

2023-12-18 17:55 UTC, vpyzhyanov commented on src/test/java/org/bot/command/CommandTest.java
> +public class CommandTest {
Неправда, вы тестируете класс `CommandProcessor`, а не Command, имя класса должно быть **правдивым** и отражать **суть** класса!

2023-12-18 17:55 UTC, vpyzhyanov commented on src/main/java/org/bot/service/JokeServiceImpl.java
> +        return jokeDAO.findJoke(id);
Ваш JokeServiceImpl - бездельник, он тупо делегирует свою работу jokeDAO. Кому нужен такой бесполезный класс?! Либо наполните его смыслом (хотя пока не видится этого смысла), либо удалите.

2023-12-18 17:58 UTC, vpyzhyanov commented on src/main/java/org/bot/dao/JokeServiceImpl.java
> +                "jdbc:postgresql://localhost:5433/" + System.getenv("DB"));
Всё ещё неправильно. Разделили учётные данные и url, хотя идут всегда вместе друг с другом. Я написал подробнее в свежем замечании

2023-12-18 18:28 UTC, Sosmunk commented on src/main/java/org/bot/util/HibernateUtils.java
> +                System.getenv("DB_PASSWORD"));
Исправлено

2023-12-18 18:28 UTC, Sosmunk commented on src/main/java/org/bot/service/JokeServiceImpl.java
> +        return jokeDAO.findJoke(id);
Будет наполнен смыслом в следующей задаче, оставлен комментарий

2023-12-18 18:29 UTC, Sosmunk commented on src/main/resources/hibernate.properties
> +hibernate.connection.url=jdbc:postgresql://localhost:5433/joker
hibernate.properties добавлен в gitignore

2023-12-18 18:53 UTC, Lapoushko commented on src/test/java/org/bot/command/CommandTest.java
> + * Тест обработки команд /help, /start, /joke, /getJoke &lt;id&gt;
исправлено

2023-12-18 18:56 UTC, Lapoushko commented on src/test/java/org/bot/command/CommandTest.java
> +    private final String FIRST_JOKE = """
Исправлено

2023-12-18 18:58 UTC, Lapoushko commented on src/main/java/org/bot/command/CommandProcessor.java
> +        return commandParser.parseMessage(command);
Исправлено

2023-12-18 18:58 UTC, Lapoushko commented on src/main/java/org/bot/bot/TelegramBot.java
> + * Класс телеграм бота
Исправлено

2023-12-18 19:02 UTC, Sosmunk commented on src/main/java/org/bot/dao/JokeDAO.java
> +                return null;
В javadoc указано что может вернуться null

2023-12-18 19:04 UTC, Sosmunk commented on src/main/java/org/bot/bot/Bot.java
> +    default void sendMessage(Long chatId, String message) {}
исправлено

2023-12-18 19:06 UTC, Sosmunk commented on src/main/java/org/bot/bot/Bot.java
> + *  Интерфейс работы ботов
исправлено

2023-12-18 19:06 UTC, Sosmunk commented on src/main/java/org/bot/bot/TelegramBot.java
> + * Класс телеграм бота
исправлено

2023-12-18 19:06 UTC, Sosmunk commented on src/main/java/org/bot/bot/TelegramBot.java
> + * Класс телеграм бота
для vk тоже

2023-12-18 19:06 UTC, Sosmunk commented on src/main/java/org/bot/command/CommandProcessor.java
> +        return commandParser.parseMessage(command);
метод убран

2023-12-19 11:06 UTC, merged

2023-12-20 19:35 UTC, Lapoushko commented on src/test/java/org/bot/FakeJokeService.java
> +public class FakeJokeService implements JokeService {
Заменили FakeJokeService на Mockito

2023-12-20 19:38 UTC, Lapoushko commented on src/main/java/org/bot/service/JokeServiceImpl.java
> +        if (getRandomJoke() == null) {
Исправлено

2023-12-20 22:09 UTC, Lapoushko commented on src/test/java/org/bot/FakeJokeService.java
> +public class FakeJokeService implements JokeService {
Мы считаем, что его тестировать не нужно